### ISSUE TITLE
Colour picker accessibility issues

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#1070]
Colour picker fields produced either via `form.color()` or by using the `js-colorpicker` class produce a number of accessibility issues/considerations.

1. The colour picker dropdown isn't keyboard accessible. It could be argued that the text field offers an accessible alternative.
2. The markup generated by the colour picker includes an input without an associated label.

To investigate and document findings.

**Comment by Stanton** [comment]
There don't seem to be any maintained colour pickers which are completely keyboard accessible, Spectrum has a keyboard branch which was submitted five years ago and in general, there's little to no actual activity on the repository and lots of outstanding pull requests. The few pickers I've seen which do offer keyboard support only allow a small list of colour options to be tabbed through rather than a full spectrum.

I've pushed a change which addresses issue 2, and removes the inaccessible input after load as we don't use it anyway, but as far as issue 1 is concerned I think we will have to lean on the plain text field being the accessible alternative.

**Comment by jamesjacobs** [comment]
Closing.

Issue 1: The text input offers an accessible alternative to the colour picker
Issue 2: Fixed by #1128
