### ISSUE TITLE
Form choice block: Unable to deselect options if set as check in helper options

### ISSUE THREAD

**Issue by Hodgy** [jadu/pulsar#193]
using 

    {{
        form.choice({
            'label': '',
            'class': 'choice--block choice--block-inline form__group--medium',
            'optimize': 'few',
            'options': [
                {"label":"Bold","value":"1","checked":true},
                {"label":"Italic","value":"2","checked":true},
                {"label":"Underline","value":"3","checked":true},
                {"label":"Strikethrough","value":"4","checked":true},
                {"label":"Format","value":"5","checked":true}
            ]
        })
    }}

the generated choices cannot be deselected.

![form_choice_deselect](https://cloud.githubusercontent.com/assets/1502446/15017142/4b9f033e-120c-11e6-86de-5879eef6d441.gif)

**Comment by Stanton** [comment]
Radio inputs can't be deselected, try switching to checkboxes instead

Option   | Type   | Description
-------- | ------ | -------------------------------------------------------
multiple | bool   | If `true`, uses checkboxes instead of radios, or passes the `multiple` attribute to the select2 element
