### ISSUE TITLE
Pulsar-wide HTML W3C Validation Fixes

### ISSUE THREAD

**Issue by nvasileiadis** [jadu/pulsar#555]
Run 'grunt validate' and resolve as many error messages as possible from the output reports generated for the HTML part of Pulsar Lexicon.

**Comment by nvasileiadis** [comment]
- Attribute “label” not allowed on element “li” at this point. Example: <li label="Lexicon" class="nav-item t-nav-item is-active">
- Attribute “placeholder” not allowed on element “select” at this point. Example: <select id="colour" multiple="" placeholder="Choose one or more" class="form__control select js-select2 select2-hidden-accessible" tabindex="-1" aria-hidden="true">
- Element “ul” not allowed as child of element “span” in this context. (Suppressing further errors from this subtree.) Example: <ul class="select2-selection__rendered">
- The “textbox” role is unnecessary for an “input” element that has no “list” attribute and whose type is “search”. Example: <input class="select2-search__field" type="search" tabindex="0" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" role="textbox" aria-autocomplete="list" placeholder="" style="width: 0.75em;">
- Element “option” without attribute “label” must not be empty.
- The “button” role is unnecessary for element “button”.
- Duplicate ID “select2-size-container”.
- The “button” role is unnecessary for element “button”
- Bad value “157px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
- The first child “option” element of a “select” element with a “required” attribute, and without a “multiple” attribute, and without a “size” attribute whose value is greater than “1”, must have either an empty “value” attribute, or must have no text content. Consider either adding a placeholder option label, or adding a “size” attribute with a value equal to the number of “option” elements.
- Attribute “append_type” not allowed on element “select” at this point. Example: <select id="select-31" append_type="button" class="form__control select">
- Element “style” not allowed as child of element “div” in this context.
-A table row was 99 columns wide and exceeded the column count established by the first row 
- Table columns in range 5…99 established by element “td” have no cells beginning in them.
- Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections.
- The “aria-labelledby” attribute must point to an element in the same document.

Lots of Duplicate IDs and label not valid inside li.

**Comment by Stanton** [comment]
> Attribute “label” not allowed on element “li” at this point. Example:

| Product | Considerations |
| -------- | --------------- |
| Pulsar    | Fix needed in nav helper |
| CMS      | Uses nav helper |
| XFP       | Uses nav helper |
| CXM     | Custom markup? | 

> Attribute “placeholder” not allowed on element “select” at this point. Example: Element “ul” not allowed as child of element “span” in this context. (Suppressing further errors from this subtree.) 

* Change needed in forms helper to ensure correct markup, any raw markup in Continuum products may or may not have the issue, but the responsibility for testing that will be with the Pulsar team member managing the UI for that product.

> The “textbox” role is unnecessary for an “input” element that has no “list” attribute and whose type is “search”. 

* Change needed in base layout or search partial to ensure correct markup, Continuum products may or may not have the issue, but the responsibility for testing that will be with the Pulsar team member managing the UI for that product.

> Element “option” without attribute “label” must not be empty.

* Open for discussion on this one but I'd vote that Pulsar or Continuum products calling this helper simply need to add `label` attributes to generate valid markup. At the moment I think it's potentially dangerous to start adding a default `label` value to fix this issue within the helper as we don't want live forms suddenly getting a new value they're not expecting. I'd say this should be resolved by adding a note to our documentation, and fixing any instances within the Lexicon by adding `label` attributes where required. 

> The “button” role is unnecessary for element “button”.

This is an 'info' message, so not critical that we fix, I'd say we fix it in the button helper(s) and hold it back for the next `major` just in case

> Duplicate ID “select2-size-container”

Lexicon issue only

> Bad value “157px” for attribute “width” on element “img”: Expected a digit but saw “p” instead

Is this raw markup in the Lexicon?

> The first child “option” element of a “select” element with a “required” attribute, and without a “multiple” attribute, and without a “size” attribute whose value is greater than “1”, must have either an empty “value” attribute, or must have no text content. Consider either adding a placeholder option label, or adding a “size” attribute with a value equal to the number of “option” elements.

Mostly an implementation issue to be fixed in the lexicon, but adding the `size` option is interesting, and could be done in the form helper.

> Attribute “append_type” not allowed on element “select” at this point.

My bad, didn't spot this in the recent change to add this functionality in. Can be fixed in form helpers with no fuss (patch)

>  Element “style” not allowed as child of element “div” in this context. 

Need more info

> A table row was 99 columns wide and exceeded the column count established by the first row Table columns in range 5…99 established by element “td” have no cells beginning in them. 

Think this is down to my lazyness using `colspan="99"`, needs adjusting where used.

> Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections. The “aria-labelledby” attribute must point to an element in the same document. 

Lexicon issue?

> Lots of Duplicate IDs

Lexicon issues

**Comment by nvasileiadis** [comment]
- Masterswitch
The error "Attribute “aria-disabled” is unnecessary for elements that have attribute “disabled”." is bound to jQueryUI.

- Modules
The errors like this 'Attribute “helpercontent” not allowed on element “div” at this point.' are bound to @mikedevelops work in dropzone.

- Settings
The duplicate ID “optional-question” error can be ignored.

- Tables
The “valign” attribute on the “td” element is obsolete. Use CSS instead. - Caused by ext.js
All the issues related to class variations of 'select2-selection' are caused by the select2.js files

- Disabled-UI
Attribute “aria-disabled” is unnecessary for elements that have attribute “disabled - Caused by jQuery
