### ISSUE TITLE
Move away from Bower

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#666]
https://bower.io/blog/

Packages currently managed by Bower will be moved under the responsibility of NPM where possible.

**Comment by mikedevelops** [comment]
My 2 cents...

One problem is once this is removed how we install Pulsar's "runtime" or "develop" dependencies, a (non ideal) solution is to keep the "lib" / "bower_components" directory committed, however I think this should be removed as part of this ticket. It isn't ideal having these committed from an architecture point of view, as well as not ideal we are opting out of patch and minor version bumps.

The reason this is a problem is because of how Jadu products currently consume Pulsar, they depend on the bower components being committed when Pulsar is installed with composer, when ideally they should be fetched with NPM (or some other trendy package manager) at the point Pulsar is installed / updated.

Having used both, I personally vote 👎  to yarn, as NPM v5 has a ["NPM 5 has stronger guarantees across versions and has a stronger deterministic lockfile"](https://yarnpkg.com/blog/2017/05/31/determinism/). Although admittedly we've had some teething issues with NPM v5, they are releasing patches monthly and they _seem_ to be clearing up.

**Comment by Stanton** [comment]
@mikedevelops are we in a position to use NPM5 today, or are there any known blockers preventing us from starting to put together a PR?

**Comment by mikedevelops** [comment]
@Stanton I can't foresee any known blockers, in fact, technically we are already using NPM v5, I am anyway, we already have a `package-lock.json` in the repo, so no work required on that front.

**Comment by Stanton** [comment]
I'm hoping the ticket number isn't a sign 🙈
