### ISSUE TITLE
Make raw filter opt-in?

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#710]
We use the `raw` filter in various places where we need to nest macros, for example:

```
{{
    html.button({
        'label': html.icon('check') ~ ' Call to Action'
    })
}}

<button class="btn btn--primary">
    <i aria-hidden="true" class="icon-ok"></i> Call to Action
</button>
```

To achieve this, we can't do any form of escaping on the `label` option and must implicitly trust that the value supplied will be safe. However, there are situations where we need to give Admins the ability to supply custom values to buttons. labels etc, so we need to come up with an alternative to using `raw` that still allows us to nest macros in the way we need. (The button example here is a simple one, there are more complex uses of `raw` in form helpers).

Without `raw`, the macro renders:

```
<button class="btn btn--primary">
    &lt;i aria-hidden="true"  class="icon-ok"&gt;&lt;/i&gt; Call to Action
</button>
```

### Option: Make `raw` opt-in behaviour

DG suggested this, and the more I try and avoid it the more I think it's going to be the only way forward. We would add a new option to helpers like button, which would allow a developer to turn on `raw` mode, it would then, depending on the design of the macro, allow unfiltered markup into the view to achieve whatever if required at the time.

```
{{
    html.button({
        'label': html.icon('check') ~ ' Call to Action',
        'raw': true
    })
}}
```

and inside the button macro we'd do something like:

```
<button{{
    attributes(options
        |exclude('caret label')
        |defaults({
            'class': 'btn'
        })
    )
}}>
    {% set label = options.label|default|strip_tags %}
    {% if options.raw is defined and options.raw != false %}
        {{- label|raw -}}
    {% else %}
        {{- label -}}
    {% endif %}
    {{- util.caret(options.caret|default) -}}
</button>
```

😎 Fail secure
😎 Make devs explicitly choose when to use raw (i.e. not when expecting user supplied inputs)
😎 Easy to search/audit where the raw flag is used in product views to sanity check the use
💀 Most impact to implement in products, would need to be part of a major version release
💀 All existing Pulsar views would need to be updated and tested

I'm not really considering suggesting it should be opt-out at this point, I can't make a good enough argument for it.

----

I'm open to any other options or new ideas, I've looked into using `string_from_template()` instead of `raw` but I don't think it would actually fix anything apart from looking less scary by not saying 'raw'. I can't create a custom filter because everything's escaped unless you use `raw` to mark it safe.

This doesn't cover all uses of `raw` either, some at the template level (like the tab helpers) simply can't be avoided, but unless we're allowing users control over that level of the template (which we don't), we should be ok.

As an aside, it's worth mentioning that this new constraint on raw would probably make us design other helpers for specific use cases, like icon buttons, which move us away from nesting the icon helper, but as I mentioned earlier form helpers are a bit of a different case.

On the plus side, we have a major version slated for early next year which will involve some end to end view testing in products, so perhaps it's an ideal time to work something like this in?

### HTML
- [x] badge
- [x] button
- [ ] countdown
- [x] div
- [x] icon
- [x] label
- [x] link
- [x] li
- [x] media
- [x] metadata
- [x] panel
- [x] progress
- [x] dropzone

### Form
- [x] content (via elem.paragraph)
- [x] end
- [x] error
- [x] fieldset_start
- [ ] group
- [x] help

### Elem
- [x] paragraph

### Nav
- [x] primary
- [x] nav_item

### Flash
- [x] message

### Rules
- [ ] block

### Tabs
- [x] content (Can't see that we can get away from using this, anything passed to tabs.content should be considered safe at the point of render)

**Comment by mikedevelops** [comment]
One option that springs to mind for me, albeit nowhere near as considered and thought out as your proposal above, would be to remove the need to nest macros/HTML in a config-driven way across the board. This would be an incredibly major change (is there one higher than major? Fundamental?) across products, however I'll take a stab at it:

```
{{ html.button.start() }}
    {{ html.icon('check') }}
    Call to Action
{{ html.button.end() }}
```

This would mean more markup for developers to write in order to create UIs, but the trade-off would be composition. 

😎 Composition
😎 Make devs explicitly choose when to use raw (i.e. not when expecting user supplied inputs)
😎 It would be easier for products to create new UI patterns using Pulsar
💀 / 😎 We would find more edge case bugs than ever before
💀 Too much flexibility might not always be the best thing to maintain
💀 Most impact to implement in products, would need to be part of a major version release
💀 All existing Pulsar views would need to be updated and tested
💀 More code required to create UIs

**Comment by Stanton** [comment]
I'm still not sure I can get on board with this way of thinking for the HTML and Form helpers, at least not without clarifying a lot of minutiae, like how would separate start/end macros work when the expected button markup changes from `<button>foo</button>` to `<input type="button" value="foo" />`, would we break the opening closing brackets across helpers so that `value` falls into the right place? For some cases it seems like it could work, for others it seems fragile (but that's from a first glance obviously).

We could, however, have this as an abstraction layer for certain cases, or more clearly, make the current helpers be an abstraction of this config-driven approach, if that makes any sense. So a current helper could still allow the current code at a high level, but use the config-driven approach internally or as a fallback for more complex UI needs.

If we went this way and replaced them wholesale, we'd need to create a new `v3` version of the helpers and run both in tandem for a while. If we did it as an abstraction, we could make it less major.

The thing that would make it a more major consideration would be if it made integrating with Symfony form helpers easier, that's still a bit of a gap in our UI provision at the moment that I'd like to close next year.

**Comment by mikedevelops** [comment]
I'd envision case where components are different, for example the `button` vs `[type="button"]`, would be different components. Both could share their class names through an internal config (not exposed to users), so their styling would be consistent. The would be composed with something liek this maybe:

```
{{ input.button('foo') }}

{{ html.button.start() }}foo{{ html.button.end() }}
```

In this instance input buttons would be composed different, because they are different.

I'm not sure I follow the abstraction layer, it seems that wherever we pass in HTML (raw, script tags escaped, or otherwise) as a configuration parameter we'll be venerable to XSS.

I understand that this is likely too fundamental to be considered work-able (although interesting point about Symfony helpers, that maybe somewhere to find some inspiration). I suspect what I'm suggesting here is putting Twig into a React / Angular / Vue shaped box. Maybe it's best this sort of approach is left for Pulsar's React / (insert library here) library.

**Comment by Stanton** [comment]
Added to Product Owner meeting agenda 25/09/2020
