### ISSUE TITLE
Select appearance in Firefox

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#856]
When expanded, selects look a little odd in firefox (see screenshot below). Note the position of the dropdown and the scrollbar. Standard unstyled selects do not have this - tested in a codepen.

![screen shot 2018-07-31 at 10 50 06](https://user-images.githubusercontent.com/756393/43452582-aea447b4-94af-11e8-98ed-a5dbbc95f862.png)

**Comment by Stanton** [comment]
I don't think it's possible to resolve this without removing all height information from select elements, which is not a change we'd be easily able to make.

> Standard unstyled selects do not have this

As soon as height is added, the issue is present.

![Screenshot 2020-09-09 at 11 11 46](https://user-images.githubusercontent.com/18653/92585822-5d6daa00-f28d-11ea-97d3-693011aa142b.png)
