### ISSUE TITLE
Large table inside tab content doesn't have horizontal scroll bar

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#923]
**Describe the bug**
When the window is small, and there is a table inside tab__content, there is no horizontal scroll bar present to see the off-screen information.

**To Reproduce**
1. Make the browser small.
2. Attempt to scroll the table.

**Expected behavior**
You should be able to scroll across the page to see the addtional information in the table.

**Screenshots**
![screen shot 2018-11-12 at 17 48 32](https://user-images.githubusercontent.com/9383439/48365728-a198bf00-e6a3-11e8-9797-5d3b8c987f72.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Latest (70)

**Additional context**
This is likely caused by the tab__content being rendered using `display: table`. And then placing a table inside this.

**Comment by Stanton** [comment]
### Verified issue
* adding `table--horizontal` does not resolve
* Rules UI doesn't collapse into responsive 'block' mode because it doesn't take into account the container width (table cell), just the viewport

### Other considerations/discussion points
* Rules UI should probably not just be constrained to the 'page' cell, and be set to colspan through the 'page', 'prefills' and 'branching' columns.
* Should Rules UI attempt to display inline fields at all in this instance, the inline version is only appropriate at very wide viewports... should there be a way to set Rules to use the block layout at all times in certain situations?

![form-rules](https://user-images.githubusercontent.com/18653/48473547-91dac100-e7f0-11e8-9925-72586c449fb6.gif)

**Comment by Stanton** [comment]
* Adding `display: flex` to `.tab__inner` allows the table to be constrained by its container
* Adding `.table--horizontal` to the table allows the table to correctly style the overflows, and add a horizontal scrollbar (this does not work without the flex change)

![screenshot 2018-11-15 at 13 27 11](https://user-images.githubusercontent.com/18653/48556697-97add080-e8dc-11e8-8b01-e6d515adf476.png)

**Side effects:**
* settings column now extends to match the height of tab__inner (observed in galaxies designer)

![screenshot 2018-11-15 at 13 39 45](https://user-images.githubusercontent.com/18653/48556711-a1cfcf00-e8dc-11e8-8dfd-9ba612cb8bd4.png)

**Comment by Stanton** [comment]
* adding `height: 1%` to `.tab__settings` forces it to shrink-to-fit, cross browser testing notwithstanding.

![screenshot 2018-11-15 at 13 49 16](https://user-images.githubusercontent.com/18653/48556940-43efb700-e8dd-11e8-86fb-4ca7986cd7f3.png)

**Comment by Stanton** [comment]
IE11: Also needs `display: flex;` adding to `.tab__content`...

![ie11](https://user-images.githubusercontent.com/18653/48562613-7bb12b80-e8ea-11e8-943f-9a8038df95b1.gif)

**Comment by Stanton** [comment]
# IE10

* No issues observed

**Comment by Stanton** [comment]
# IE9

* The whole tab inner has been made to scroll if the content's exceed the boundary (settings UI only)

![flex-ie9](https://user-images.githubusercontent.com/18653/48617527-9fc64880-e98e-11e8-8863-70451c15aa3b.gif)

**Comment by Stanton** [comment]
> Should be able to disable the same height thing by applying `align-items: flex-start;` to `.tab__inner` - https://stackoverflow.com/a/33043084/1600814

Giving this a shot, cheers!

**Comment by Stanton** [comment]
# Safari

![flex-safari](https://user-images.githubusercontent.com/18653/48619054-2a10ab80-e993-11e8-9168-b20b754b41f1.gif)

**Comment by Stanton** [comment]
# Firefox

![flex-firefox](https://user-images.githubusercontent.com/18653/48619133-6c39ed00-e993-11e8-9437-0c71d9311d14.gif)
