### ISSUE TITLE
New toggle switch doesn't allow tooltips on label or switch

### ISSUE THREAD

**Issue by langy** [jadu/pulsar#93]
All 'extra' attributes get applied to the input checkbox, which is hidden, so things like tooltips can't be used.

**Comment by Stanton** [comment]
Wouldn't recommend using a tooltip on a toggle switch, and since this ticket was created labels can accept guidance popovers which should be sufficient, unless a specific use case is presented.

As a side note, a tooltip could be passed to the entire `form__group` by wrapping it in a containing `<div>` which has the related tooltip params.
