### ISSUE TITLE
moment.js locale is excluded in .gitattributes

### ISSUE THREAD

**Issue by jamesjacobs** [jadu/pulsar#976]
**Describe the bug**
The directory containing moment.js's locale data is ignored in .gitattributes and therefore not installed when installing pulsar in third party software via composer. Therefore moment.js falls back to the default locale and other locales cannot be used.

https://github.com/jadu/pulsar/blob/abdbe741266ed0f3b41b1466933050cc401686e6/.gitattributes#L221

**Expected behavior**
Locale data should be included and available for use.

**Comment by mikedevelops** [comment]
Another good opportunity here to remove moment from committed dependencies altogether and fix on products, rather than simply remove that line from `.gitattributes`

Whilst we remain distributed by composer we'd need to document a list of dependencies that users would need to install (and at which versions) once we remove the committed dep.

Perhaps we could look into automating this with post-install composer scripts? Although might have to weigh up hoe best practice scalable that is.

**Comment by Stanton** [comment]
> Another good opportunity here to remove moment from committed dependencies altogether and fix on products, rather than simply remove that line from `.gitattributes`
> 
> Whilst we remain distributed by composer we'd need to document a list of dependencies that users would need to install (and at which versions) once we remove the committed dep.
> 
> Perhaps we could look into automating this with post-install composer scripts? Although might have to weigh up how best practice scalable that is.

This is a separate, larger scoped piece of work that should happen outside of this specific change request.
